version: "2.3"
services:
  base: &base
    user: $UID:$GID
    image: $IMAGENAME
    network_mode: "bridge"
    volumes:
      - $PWD:/src
    environment:
      - HOME=/tmp
  cpu:
    <<: *base
    build:
      context: .
  gpu:
    <<: *base
    runtime: nvidia
  jupyter:
    <<: *base
    ports:
      - "$PORT:$PORT"
    command:
      bash -c "
      jupyter lab --ip 0.0.0.0 --allow-root --port $PORT
      "
