version: 2
jobs:
  build:
    machine: true
    environment:
      - IMAGENAME: chainer-docker
    steps:
      - checkout
      - run:
          name: Build application Docker image
          command: |
              docker build -t $DOCKER_USER/$IMAGENAME .
      - deploy:
          name: Push application Docker image
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                docker push $DOCKER_USER/$IMAGENAME
              fi

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 1 * * *" # UTC (am 10:00 JST every day)
          filters:
            branches:
              only:
                - master
    jobs:
      - build